### ISSUE TITLE
Make WalletManager Tests run faster

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo-sharp#305]
Our current wallet tests are using the default Scrypt Parameters. This causes the test to be extremely slow. Mock and replace this so the tests run faster.

**Comment by shargon** [comment]
I think that slow test is not a problem because you check the real logic, in fact, this test should check that spend this amount time, because if don't this encryption is wrong

**Comment by lock9** [comment]
@aboimpinto  what do you think? How would you improve it?

**Comment by aboimpinto** [comment]
I agree with you @shargon, but, the heavy parts of the code can be isolated in another class and injected into the Wallet.
Another thing that spend a lot of time if the access to the FileSystem to read configuration or the wallet. This kind of heavy operation can be and should be isolated.

**Comment by shargon** [comment]
I will close this because the UT is doing his job, if you consider that is important please be free to reopen again.
