### ISSUE TITLE
Use the local branch code to deploy in the containerize environment

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-sharp#342]
The current test environment that use the container obtain the code from the GitHub, development branch by default. 
This feature is important to proceed with test on the current core pushed to the server.

There should be a way to build the container infrastructure using user git addresses or local code to test the code before the Pull-Request.

**Comment by nunojusto** [comment]
Do you mean building the container using local branch code?
Interesting...

**Comment by aboimpinto** [comment]
I cannot tell you if it's building or not, but, when you clone code from the GitHub, I would like to use a branch from my personal GitHub account.

**Comment by nunojusto** [comment]
Ok, I get it. You want to use the containers ecosystem to test your draft code...
Let me work on this...

**Comment by nunojusto** [comment]
Done

**Comment by aboimpinto** [comment]
tests and looks good... tkx @nunojusto
