### ISSUE TITLE
Travis to test execution of the Node

### ISSUE THREAD

**Issue by nunojusto** [CityOfZion/neo-sharp#346]
**Overview:**
Following last issue we had (https://github.com/CityOfZion/neo-sharp/issues/344) we need to put Travis working for us to test if the node really can start after a Pull Request.

**To-do**
So, Travis today is testing if the Node can be compiled but nothing more.
Trvais should run the Node (after building his container) and check if it's running. Maybe checking it several times, before assume it's stable and can flag it with a Green Go.

**Comment by nunojusto** [comment]
I see that we have port 8000 open after the Node is running sucessfuly. I can start with that.
Is there any 'remote' tests I can do for it, that can reply with a known code?

**Comment by aboimpinto** [comment]
this port is open even if the we don't run the command "network start"??

**Comment by nunojusto** [comment]
Yes, it is

**Comment by aboimpinto** [comment]
@osmirnov maybe this is a bug. Until the command "> network start" no port should be open .. right?

maybe in the future this "feature" will change,

**Comment by nunojusto** [comment]
My bad @aboimpinto , I was testing the exposed container port instead of the inside port.
So, you're right, only when "network start" is in place, the port is open.

And than causes even more dificulty for us. Because how can we instruct Travis to do neo-sharp console commands.

**Comment by aboimpinto** [comment]
maybe we can have a command when we call the neo-sharp that start the network after the console app is running
