### ISSUE TITLE
Is not Synchronizing

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-sharp#357]
there are a issue during the creating of the Message Handler the resolve of the message handler is throwing an exception.
This code is very complex for something very easy. Going to replace this code with injection of a list of message handlers and use the Strategy Pattern to choose witch handler should be used.

**Comment by aboimpinto** [comment]
during the debug, found another issue regarding the connection with the peers. For some reason that I don't know, the peer stop sending the expected data to the node and we get an exception that is been swallow by the async/await pattern.

![image](https://user-images.githubusercontent.com/1231687/45725094-5ee1cb80-bbb9-11e8-87ff-b40b47ff736c.png)

After this error, the peer is disconnected and there is no information on the console and even the comand "> nodes" continue to show the information 
![image](https://user-images.githubusercontent.com/1231687/45725136-9ea8b300-bbb9-11e8-8281-ba786083f257.png)

**Comment by aboimpinto** [comment]
I'm testing accessing the TestNet and it's possible the server think it's a DDoS attack and close the connection.

**Comment by aboimpinto** [comment]
@osmirnov Looks like this problem only happen when we have multiple peers to connect. With one peer only we don't experience this issue.

When we have multiple peer, some of the handlers try to send the message "consensus" and when that happen the server reset the connection.

With help of @lock9 we create a workaround where we never send this message type. 
https://github.com/CityOfZion/neo-sharp/pull/423
This need to be verified and fixed.

**Comment by shargon** [comment]
Fixed
