### ISSUE TITLE
Peer disconnect / reconnect concept

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-sharp#429]
When a peer disconnect, the Server class should be informed in order to remove this peer from the list of online peer.
This class should be have the responsibility to proceed the re-connection of the peer.

**Comment by aboimpinto** [comment]
@osmirnov I create this issue related with the peer reconnect. Is your commit try to solve this? Can you link?

**Comment by osmirnov** [comment]
It is done I don't remember when :(
