### ISSUE TITLE
TODO: Build a Dockerfile to run neo-sharp Node in ARM architecture

### ISSUE THREAD

**Issue by nunojusto** [CityOfZion/neo-sharp#444]
Make possible to run neo-sharp Node in ARM CPU architecure.
Possible target machines are: Raspberry Pi; Banana Pi; NanoPi; ODROID and so on...

This can have a huge importance to enable IOT dApps integration.

**Comment by nunojusto** [comment]
I've been working on this for several days and after many hammer code and refinements I have the demo MVP ready.

![image](https://user-images.githubusercontent.com/21068187/46066722-0ab48980-c16d-11e8-9e14-9bbb32bbdf57.png)

I will soon consolidate all the work in a Dockerfile, to provide people a fast way to install it.

**Comment by aboimpinto** [comment]
this is a great initiative... :)

**Comment by shargon** [comment]
I need to compile HyperVM on ARM :P

**Comment by nunojusto** [comment]
> I need to compile HyperVM on ARM :P
@shargon 
Open an issue there ;)
We can work on that

**Comment by nunojusto** [comment]
-= Assigned to nunojusto =-
