### ISSUE TITLE
Todo:  Fix broadcast

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo-sharp#471]
We are broadcasting messages to ours seeds, this causes us to be disconnected.
I debugged it with Wireshark and I noticed that neo-cli does not send this messages to the seeds.

I commented the lines in Sever.cs that does that (otherwise we can't sync the chain).
I believe the correct thing to do is to send only to "secondary" peers.

**Comment by aboimpinto** [comment]
I never thought that could be a problem. I though that after a successful synchronization the node should send to peers ... this make sense to propagate blocks over the network.

**Comment by lock9** [comment]
You are correct, I double checked the current implementation, and it seems that it send the blocks to the seeds too. I'll check if we are not sending the messages in an incorrect format
