### ISSUE TITLE
Include Code Analysis rules to the build environment

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-sharp#499]
In order to reduce the discussion about how the code should look like and to avoid arguments like: "I read prefer like this..:" or "Is more readable like this..." we should implement the Code Analysis rules to rule code style.

At the begin the non-conform pieces of code should appear as warning and after the team give effort to remove all the warnings, on every build the non-conform code should be be marked as error and we should not be able to compile the code.

There are nuget packages to add Code Analysis and Style Cop rules to the .NET Core Projects:
* https://carlos.mendible.com/2017/08/24/net-core-code-analysis-and-stylecop/
* https://carlos.mendible.com/2018/04/05/adding-code-analysis-and-stylecop-checks-to-net-core-projects-with-dotnet-addcasa/

**Comment by aboimpinto** [comment]
add the CodeAnalysis and StyleCop described in productive code and not in the test code.

3869 warnings

**Comment by aboimpinto** [comment]
final number: 12.015 warning

**Comment by shargon** [comment]
Good job! i will close it because is merged
