### ISSUE TITLE
Replace Exception thrown by our code with custom exceptions

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo-sharp#506]
We are not creating custom exceptions, so it becomes hard to track if the root of the issue is in our code or in an external code. We should replace any "throw new Exception()" in our code with "throw new 'CustomException'()". We should also change the catch statements to catch this exceptions (when reasonable)

**Comment by aboimpinto** [comment]
I'm not sure that custom exception will resolve the issue. I think that we should move away from using exception in case of workflow errors and return a structure with bool value and the reason why the operation didn't run well.

**Comment by lock9** [comment]
@aboimpinto  I agree that we should not throw exceptions in expected results, but we do have some places where I think it is reasonable to throw an exception, like when we receive an invalid message. You will notice that in this particular part of the code, returning a bool won't help, because it is a loop.
