### ISSUE TITLE
Prompt coloring looks weird in PowerShell

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neo-sharp#515]
I have default blue PowerShell and we draw all prompt output using black background. Is any way to acquire default background of the console?

**Comment by shargon** [comment]
We should save the current background color on start, or i think that is not possible

**Comment by osmirnov** [comment]
What's about the transparent background?

**Comment by shargon** [comment]
There is no transparent color, and when you exit from the client, preserve the black foreground too, was fixed on https://github.com/CityOfZion/neo-sharp/pull/526
