### ISSUE TITLE
Testing Sync Algorithm

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/neo-sharp#518]
Testing last Sync Algorithm deployed by @osmirnov on 21.10.2018

**Comment by aboimpinto** [comment]
After +/- 390.000 blocks the system start to degrade and create more and more thread (reach a total of 41) and when reach 600.000 blocks processed the process was using 15G of memory

**Comment by shargon** [comment]
![image](https://user-images.githubusercontent.com/3167973/47292147-6bb56d00-d606-11e8-9e2a-303bcb9fb4fa.png)

Something doesn't match

**Comment by shargon** [comment]
![image](https://user-images.githubusercontent.com/3167973/47292369-04e48380-d607-11e8-84f1-54dbf9bb1af2.png)

This method is consuming a lot of memory, is wrong, i will patch this

**Comment by shargon** [comment]
@aboimpinto Your tests was very helpful to find and fix this issue, thanks!

**Comment by osmirnov** [comment]
This is for sure a bug. The second param for Range is **count**. So it should be toHeight - fromHeight.

**Comment by aboimpinto** [comment]
I left the sync run for some hours and the result is that is stuck in the Block 1.271.699. I already experience this happen when the block persistence try to persist the transactions. I don't know witch transaction is blowing up but it's a miner transaction or a claim transactions

![image](https://user-images.githubusercontent.com/1231687/47312768-8525db80-d63d-11e8-8fb0-e565d9b7c166.png)

The memory consummation is stable now but the number of the open thread is a little bit high at this point (22)


the nodes outputs
![image](https://user-images.githubusercontent.com/1231687/47312649-35dfab00-d63d-11e8-8012-cb5e4a47bfc7.png)

**Comment by shargon** [comment]
This is other bug, @aboimpinto the chain was synchronized without problems

![image](https://user-images.githubusercontent.com/3167973/47453240-8cc7ba80-d7cc-11e8-9940-d5966b7a04bc.png)

The problem here was a memory issue.
