### ISSUE TITLE
Fix typos in command help text

### ISSUE THREAD

**Issue by jnlewis** [CityOfZion/neo-sharp#541]
The following commands have wrong help texts:
`[PromptCommand("import wif", Category = "Wallet", Help = "Close wallet")]`
`[PromptCommand("import nep2", Category = "Wallet", Help = "Close wallet")]`
`[PromptCommand("account export wif", Category = "Account", Help = "Exports an account in nep-2 format")]`

**Comment by jnlewis** [comment]
I'm working on this issue.

**Comment by jnlewis** [comment]
No permission to create branch, can't make pull request on dev.

**Comment by osmirnov** [comment]
@jnlewis thank you for helping with this. You can fork the project, create a branch and submit PR against original development from your branch.
