### ISSUE TITLE
CheckIfPasswordMatchesOpenWallet does not always throw correct exception

### ISSUE THREAD

**Issue by jnlewis** [CityOfZion/neo-sharp#544]
The NEP6WalletManager.CheckIfPasswordMatchesOpenWallet does not throw AccountsPasswordMismatchException exception when wallet password is not in cache. This can be reproduced as such: Open an existing wallet.

> wallet create testwallet.json
> wallet close (This is to re-open the wallet to clear the password cache)
> wallet open tetswallet.json
> account create
> (Enter wrong password exception; is thrown instead of showing "invalid password")

This is due to InvalidNEP2Exception is not of type FormatException:
![wallet-check-password-exception](https://user-images.githubusercontent.com/3898665/48060365-c77f1900-e1f6-11e8-8a74-b8170fcc163b.JPG)

**Comment by osmirnov** [comment]
Good catch!
