### ISSUE TITLE
Support for transaction height

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neo-sharp#557]
There are VM calls "System.Blockchain.GetTransactionHeight" and "Neo.Blockchain.GetTransactionHeight". We need to store height for transactions.

**Comment by shargon** [comment]
We need a new index? How is this done in the official repository?

**Comment by osmirnov** [comment]
They get this from transaction record offset in LevelDB. Yes I think it should extra field `Id` or something.

**Comment by shargon** [comment]
We can use a class like this?

```csharp
class StoredTx
{
 uint Height;
 Transaction Tx;
}

```

**Comment by osmirnov** [comment]
Could we extend `Transaction` itself because we many derived classes as `InvocationTransaction`?
